"use client"
import './globals.css'
import logo from '../public/logo-gray.png'
import { Provider } from 'react-redux';
import { store } from '@/redux/store/store';
import { useEffect, useState } from 'react';
import Cookies from 'js-cookie';
import { profileDetails } from './api/userAPI';
import Footer from '@/src/components/footer/page';
// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

const footerData={
  logo,
  colums:[
    {
      name:"quick links",
      items:[
        {
          text:"dashboard",
          link:"/user/dashboard"
        },
        {
          text:"orders",
          link:"/user/orders"
        },
        {
          text:"cart",
          link:"/user/cart"
        }
      ]
    },
    {
      name:"Make moneny with us",
      items:[
        {
          text:"become seller",
          link:"#"
        },
        {
          text:"become delivery parter",
          link:"#"
        },
        {
          text:"Become an Affliate",
          link:"#"
        }
      ]
    }
  ]
}

export default function RootLayout({ children }) {
 
  return (
    // <AuthProvider>
    <html lang="en">

      <body >
        <Provider store={store} >
          {children}

        </Provider>
        <Footer data={footerData}/>
      </body>
    </html>
    // </AuthProvider>
  )
}
