"use client"
import './globals.css'
import Navbar from '@/src/components/navbar/page'
import logo from '../public/logo.png'
import { FaSearch, FaShoppingCart, FaUser, FaAngleDown, FaHeart, FaAngleUp } from "react-icons/fa";
import { CiDeliveryTruck, CiLogout } from "react-icons/ci";
import { BsShop } from "react-icons/bs";
import { PiSignInLight, PiPackageBold } from "react-icons/pi";
import { MdDashboard, MdOutlineMenu, MdClose } from "react-icons/md";
import { Provider } from 'react-redux';
import { store } from '@/redux/store/store';
import { useEffect, useState } from 'react';
import Cookies from 'js-cookie';
import { profileDetails } from './api/userAPI';
// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }


export default function RootLayout({ children }) {
 
  return (
    // <AuthProvider>
    <html lang="en">

      <body >
        <Provider store={store} >
          {children}

        </Provider>
      </body>
    </html>
    // </AuthProvider>
  )
}
